# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python-code-examples',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/python-code-examples',
                'lib_path': 'python_code_examples'},
  'syms': {'python_code_examples.core': {'python_code_examples.core.foo': ('core.html#foo', 'python_code_examples/core.py')}}}
